name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
steps:
 - name: Checkout
   uses: action/checkout@2.3.2
 - name: setup JDK
   uses: actions/upload-artifact@v2.1.4
   with:
    name: app
    path: app/build/outputs/app-debug.apk

 

